apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
    - image: ghcr.io/antoniamikey/skaffold-demo
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}

deploy:
  kubectl:
    manifests:
      - deployment.yaml
      - service.yaml
      - ingress.yaml
