FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the src folder to /app in the container
COPY src/ ./src

CMD ["python", "src/start_server.py"]