apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - protocol: TCP
      port: 6379  # Default Redis port
  selector:
    io.kompose.service: redis
