apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: docker.io/antoniamikey/webapi
          name: web
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
          resources: {}
      restartPolicy: Always

