apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    io.kompose.service: web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: web

